env: "local"

app:
  name: "uni-auth"

log:
  level: "debug"

pg:
  url: "postgres://postgres:postgres@localhost:5432/uni-auth"
  pool_max: 2

http:
  port: 8080
  timeout: 4s
  idle_timeout: 30s

grpc:
  port: 8081

swagger:
  enabled: true

jwt:
  access_sign_key: "access_sign_key"
  access_token_ttl: 30m

  refresh_sign_key: "refresh_sign_key"
  refresh_token_ttl: 24h

redis:
  host: "localhost:6379"
  db: 1

email_sender:
  smtp_host: "smtp.gmail.com"
  smtp_port: "587"
  email_alias: "no-reply@uni-auth.com"